### PR TITLE
fix: invalid new-expression of abstract class type ‘BlobDetector’

### PR DESCRIPTION
**Pull request by muellerbernd**
On archlinux and nixos I had to apply this change to make the package build.

### CODE REVIEW

**Comment by lopsided98** [comment]
Did you test this? This looks like it will cause infinite recursion to me.

**Comment by lopsided98** [comment]
This issue is discussed here: https://github.com/rst-tu-dortmund/costmap_converter/issues/38

**Comment by muellerbernd** [comment]
It compiles and the planner works in my setups. But I will try the suggestions from the issue you mentioned.

**Comment by lopsided98** [comment]
Are you actually using the `CostmapToDynamicObstacles` plugin? I don't see how this patch could work correctly.

**Comment by muellerbernd** [comment]
I am closing this, because I don't use the 'CostmapToDynamicObstacles' and #41 would be the better solution

**Pull request closed without merging**
